[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
shiba = "2jf35bawHobk2KBFDnemtR1DJ1e3XzygnuuQupCbBAJP"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/metaplex_token_metadata_program.so"

[[test.genesis]]
address = 'cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ'
program = 'tests/candy_machine.so'

[[test.genesis]]
address = 'CndyV3LdqHUfDLmE5naZjVN8rBZz4tqhdefbAnjHG3JR'
program = 'tests/candy_machine_core.so'

[[test.genesis]]
address = 'Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g'
program = 'tests/guard.so'

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/omg.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
